In [18]:
print("Hello world!!")

Hello world!!

In [19]:
# NumPy

In [20]:
import numpy as np

# Activity 1: Creating an array
array = np.array([14, 28, 33, 45, 51, 67])
print(array)

arrayArange = np.arange(60, 68, 2)
print(arrayArange)

arrayLinspace = np.linspace(0, 10, 2, dtype=int)
print(arrayLinspace)

[14 28 33 45 51 67]
[60 62 64 66]
[ 0 10]

In [21]:
#Activity 2: Matrix operation

A = np.array([[12, 25], [98, 67]])
B = np.array([[55, 82], [73, 21]])

print(A + B)
print()
print(A - B)
print()
print(A * B)
print()
print(A @ B)

[[ 67 107]
 [171  88]]

[[-43 -57]
 [ 25  46]]

[[ 660 2050]
 [7154 1407]]

[[ 2485  1509]
 [10281  9443]]

In [22]:
# Activity 3: Statistics

marks = np.array([99, 89, 93, 100, 67, 85])

np.min(marks)
print(np.min(marks))

np.max(marks)
print(np.max(marks))

np.mean(marks)
print(np.mean(marks))

np.std(marks)
print(np.std(marks))

67
100
88.83333333333333
11.081766806586193

In [23]:
'''
Take the weather data of last 1 month of udupi/ manipal
1. Find which is the hotest and the coldest day.
2. Calculate the average temperatue
3. And what days the temperature was above 35
'''

'\nTake the weather data of last 1 month of udupi/ manipal\n1. Find which is the hotest and the coldest day.\n2. Calculate the average temperatue\n3. And what days the temperature was above 35\n'

In [24]:
weatherData = np.array([27.4, 28.8, 28.8, 30.0, 27.4, 27.8, 29.1, 28.9, 29.7, 28.9, 29.6, 29.7, 29.6, 29.1, 27.8, 29.1, 27.4, 29.9, 28.6, 29.9, 29.4, 29.4, 27.7, 27.9, 30.4, 30.3, 29.8, 30.5, 28.8, 27.3, 28.2])

print("Max temperature", np.max(weatherData))
print(np.min(weatherData))

print(np.average(weatherData))

print(weatherData[weatherData > 27.9])

Max temperature 30.5
27.3
28.941935483870967
[28.8 28.8 30.  29.1 28.9 29.7 28.9 29.6 29.7 29.6 29.1 29.1 29.9 28.6
 29.9 29.4 29.4 30.4 30.3 29.8 30.5 28.8 28.2]

In [25]:
weatherDataWithDate = np.array([
  ["2026-07-01", 27.4],
  ["2026-07-02", 28.8],
  ["2026-07-03", 28.8],
  ["2026-07-04", 30.0],
  ["2026-07-05", 27.4],
  ["2026-07-06", 27.8],
  ["2026-07-07", 29.1],
  ["2026-07-08", 28.9],
  ["2026-07-09", 29.7],
  ["2026-07-10", 28.9],
  ["2026-07-11", 29.6],
  ["2026-07-12", 29.7],
  ["2026-07-13", 29.6],
  ["2026-07-14", 29.1],
  ["2026-07-15", 27.8],
  ["2026-07-16", 29.1],
  ["2026-07-17", 27.4],
  ["2026-07-18", 29.9],
  ["2026-07-19", 28.6],
  ["2026-07-20", 29.9],
  ["2026-07-21", 29.4],
  ["2026-07-22", 29.4],
  ["2026-07-23", 27.7],
  ["2026-07-24", 27.9],
  ["2026-07-25", 30.4],
  ["2026-07-26", 30.3],
  ["2026-07-27", 29.8],
  ["2026-07-28", 30.5],
  ["2026-07-29", 28.8],
  ["2026-07-30", 27.3],
  ["2026-07-31", 28.2]
])

temperature = weatherDataWithDate[:, 1].astype(float)
print(temperature)

[27.4 28.8 28.8 30.  27.4 27.8 29.1 28.9 29.7 28.9 29.6 29.7 29.6 29.1
 27.8 29.1 27.4 29.9 28.6 29.9 29.4 29.4 27.7 27.9 30.4 30.3 29.8 30.5
 28.8 27.3 28.2]

In [26]:
# Pandas

In [27]:
# Activity 1: Create dataframe
import pandas as pd

student = {
    "name": ["V", "A", "B", "C", "D"],
    "age": [22, 23, 34, 27, 38],
    "marks": [100, 95, 88, 93, 91]
}

dataframe = pd.DataFrame(student)

dataframe

  name  age  marks
0    V   22    100
1    A   23     95
2    B   34     88
3    C   27     93
4    D   38     91

In [28]:
# Activity 2: Reading datasets

from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)

df = iris.frame

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [29]:
# Activity 3: Basic operations

# df.info()

# df.describe()

# df.shape

df.columns

# df.tail()

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [30]:
# Activity 4: Selecting data

# df[['sepal length (cm)', 'target']]

df.iloc[:5]

# df.loc[10: 20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [31]:
# Activity 5: Filtering

df[df['target'] == 1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1
60,5.0,2.0,3.5,1.0,1
61,5.9,3.0,4.2,1.5,1
62,6.0,2.2,4.0,1.0,1
63,6.1,2.9,4.7,1.4,1
64,5.6,2.9,3.6,1.3,1
65,6.7,3.1,4.4,1.4,1
66,5.6,3.0,4.5,1.5,1
67,5.8,2.7,4.1,1.0,1
68,6.2,2.2,4.5,1.5,1
69,5.6,2.5,3.9,1.1,1
70,5.9,3.2,4.8,1.8,1
71,6.1,2.8,4.0,1.3,1
72,6.3,2.5,4.9,1.5,1
73,6.1,2.8,4.7,1.2,1
74,6.4,2.9,4.3,1.3,1
75,6.6,3.0,4.4,1.4,1
76,6.8,2.8,4.8,1.4,1
77,6.7,3.0,5.0,1.7,1
78,6.0,2.9,4.5,1.5,1
79,5.7,2.6,3.5,1.0,1
80,5.5,2.4,3.8,1.1,1
81,5.5,2.4,3.7,1.0,1
82,5.8,2.7,3.9,1.2,1
83,6.0,2.7,5.1,1.6,1
84,5.4,3.0,4.5,1.5,1
85,6.0,3.4,4.5,1.6,1
86,6.7,3.1,4.7,1.5,1
87,6.3,2.3,4.4,1.3,1
88,5.6,3.0,4.1,1.3,1
89,5.5,2.5,4.0,1.3,1
90,5.5,2.6,4.4,1.2,1
91,6.1,3.0,4.6,1.4,1
92,5.8,2.6,4.0,1.2,1
93,5.0,2.3,3.3,1.0,1
94,5.6,2.7,4.2,1.3,1
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1

In [32]:
# Activity 6: Sorting

df.sort_values(by='sepal length (cm)')

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
13,4.3,3.0,1.1,0.1,0
8,4.4,2.9,1.4,0.2,0
42,4.4,3.2,1.3,0.2,0
38,4.4,3.0,1.3,0.2,0
41,4.5,2.3,1.3,0.3,0
...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
135,7.7,3.0,6.1,2.3,2
131,7.9,3.8,6.4,2.0,2

In [33]:
# Assignment

"""
Use the titanic dataset
1. Total number of passengers
2. Find the average age of the survivors and the non survivors
3. List the passengers who are older than 60 years
4. Find the average fare for each passenger class
"""

'\nUse the titanic dataset\n1. Total number of passengers\n2. Find the average age of the survivors and the non survivors\n3. List the passengers who are older than 60 years\n4. Find the average fare for each passenger class\n'

In [34]:
titanic = pd.read_csv("./titanic.csv")

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
print("Total number os passengers", len(titanic))

Total number os passengers 891

In [36]:
survivors = titanic[titanic['Survived'] == 1]['Age'].dropna()

print(np.average(survivors))

nonSurvivors = titanic[titanic['Survived'] == 0]['Age'].dropna()

print(np.average(nonSurvivors))

28.343689655172415
30.62617924528302

In [37]:
titanic[titanic['Age'] > 60].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

In [38]:
passengerClass1 = titanic[titanic['Pclass'] == 1]
print("Average of passenger class 1", np.average(passengerClass1['Fare']))

passengerClass2 = titanic[titanic['Pclass'] == 2]
print("Average of passenger class 2", np.average(passengerClass2['Fare']))

passengerClass3 = titanic[titanic['Pclass'] == 3]
print("Average of passenger class 3", np.average(passengerClass3['Fare']))

Average of passenger class 1 84.1546875
Average of passenger class 2 20.662183152173913
Average of passenger class 3 13.675550101832993